/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goodm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.ListModel;

/**
 *
 * @author HERMES
 */
//TODO: (COOL FEATURE) Add a Remove Dead button.
//TODO: (COOL VISUAL) Make the UI not cause blindness, vomits and psychosis.
public class GUI extends javax.swing.JFrame {
    
    List<Character> characters = new ArrayList<Character>();
    DefaultListModel<String> dieJListModel = new DefaultListModel();
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        stunLabel.setVisible(false);
        stunText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        physicalLabel = new javax.swing.JLabel();
        initiativeLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        physicalText = new javax.swing.JTextField();
        npcInitiativeText = new javax.swing.JTextField();
        stunLabel = new javax.swing.JLabel();
        stunText = new javax.swing.JTextField();
        healthRadioButton = new javax.swing.JRadioButton();
        initiativeBonusLabel = new javax.swing.JLabel();
        initiativeBonusText = new javax.swing.JTextField();
        rollRadioButton = new javax.swing.JRadioButton();
        updateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        characterJList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        dieJList = new javax.swing.JList<>();
        nextTurnButton = new javax.swing.JButton();
        makeHisTurnButton = new javax.swing.JButton();
        forceRollButton = new javax.swing.JButton();
        sortListButton = new javax.swing.JButton();
        add5IniButton = new javax.swing.JButton();
        substract5IniButton = new javax.swing.JButton();
        pcInitiativeText = new javax.swing.JTextField();
        equalsLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        rollDieButton = new javax.swing.JButton();
        rollDieSpinner = new javax.swing.JSpinner();
        saveCharacterButton = new javax.swing.JButton();
        loadCharacterButton = new javax.swing.JButton();
        characterToLoadText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Name");

        physicalLabel.setText("Health");

        initiativeLabel.setText("Initiative");

        physicalText.setText("0");

        npcInitiativeText.setText("0");

        stunLabel.setText("Stun");

        stunText.setText("0");

        healthRadioButton.setSelected(true);
        healthRadioButton.setText("Simplified");
        healthRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        initiativeBonusLabel.setText("d6 +");

        initiativeBonusText.setText("0");

        rollRadioButton.setSelected(true);
        rollRadioButton.setText("Roll");

        updateButton.setLabel("Add/Update");

        characterJList.setMaximumSize(new java.awt.Dimension(215, 80));
        characterJList.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(characterJList);

        jScrollPane2.setViewportView(dieJList);

        nextTurnButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nextTurnButton.setText("Next Pass");

        makeHisTurnButton.setText("Make His Turn");
        makeHisTurnButton.setActionCommand("Turn to this char");

        forceRollButton.setText("Force Roll");

        sortListButton.setText("Sort List");
        sortListButton.setActionCommand("sortListButton");

        add5IniButton.setName(""); // NOI18N

        pcInitiativeText.setText("0");

        equalsLabel.setText("=");

        deleteButton.setText("Delete");

        rollDieButton.setText("Roll Die");

        saveCharacterButton.setText("Save Character");

        loadCharacterButton.setText("Load Character");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nextTurnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sortListButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rollDieSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rollDieButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(nameLabel)
                                .addGap(4, 4, 4)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(healthRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(physicalLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rollRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(initiativeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(npcInitiativeText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(physicalText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stunLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stunText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(initiativeBonusLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(initiativeBonusText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(equalsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pcInitiativeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(substract5IniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(add5IniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(saveCharacterButton))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(updateButton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(deleteButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(makeHisTurnButton)))
                                .addGap(6, 6, 6)
                                .addComponent(forceRollButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadCharacterButton)
                            .addComponent(characterToLoadText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveCharacterButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthRadioButton)
                    .addComponent(physicalLabel)
                    .addComponent(physicalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stunLabel)
                    .addComponent(stunText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterToLoadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rollRadioButton)
                                .addComponent(initiativeLabel)
                                .addComponent(npcInitiativeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(initiativeBonusLabel)
                                .addComponent(initiativeBonusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pcInitiativeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(equalsLabel))
                            .addComponent(substract5IniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(add5IniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(updateButton)
                                .addComponent(deleteButton))
                            .addComponent(makeHisTurnButton)
                            .addComponent(forceRollButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nextTurnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortListButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rollDieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollDieSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadCharacterButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JRadioButton getHealthRadioButton() {
        return healthRadioButton;
    }

    public JButton getNextTurnButton() {
        return nextTurnButton;
    }

    public void setNextTurnButton(JButton nextTurnButton) {
        this.nextTurnButton = nextTurnButton;
    }

    public JButton getSortListButton() {
        return sortListButton;
    }

    public void setSortListButton(JButton sortListButton) {
        this.sortListButton = sortListButton;
    }

    public void setHealthRadioButton(JRadioButton healthRadioButton) {
        this.healthRadioButton = healthRadioButton;
    }

    public JLabel getInitiativeBonusLabel() {
        return initiativeBonusLabel;
    }

    public void setInitiativeBonusLabel(JLabel initiativeBonusLabel) {
        this.initiativeBonusLabel = initiativeBonusLabel;
    }

    public JTextField getInitiativeBonusText() {
        return initiativeBonusText;
    }

    public void setInitiativeBonusText(JTextField initiativeText) {
        this.initiativeBonusText = initiativeText;
    }
    
    public void setPcInitiativeText(JTextField initiativeText) {
        this.pcInitiativeText = initiativeText;
    }
    
    public JTextField getPcInitiativeText() {
        return pcInitiativeText;
    }

    public JLabel getInitiativeLabel() {
        return initiativeLabel;
    }

    public void setInitiativeLabel(JLabel initiativeLabel) {
        this.initiativeLabel = initiativeLabel;
    }

    public JTextField getNpcInitiativeText() {
        return npcInitiativeText;
    }

    public void setNpcInitiativeText(JTextField initiativeBonusText) {
        this.npcInitiativeText = initiativeBonusText;
    }

    public JList<String> getjList1() {
        return characterJList;
    }

    public void setjList1(JList<String> jList1) {
        this.characterJList = jList1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }
    
    public JButton getSaveCharacterButton(){
        return this.saveCharacterButton;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public void setNameLabel(JLabel nameLabel) {
        this.nameLabel = nameLabel;
    }
    
    public JLabel getEqualsLabel(){
        return equalsLabel;
    }
    
    public JTextField getNameText() {
        return nameText;
    }

    public void setNameText(JTextField nameText) {
        this.nameText = nameText;
    }

    public JLabel getPhysicalLabel() {
        return physicalLabel;
    }

    public void setPhysicalLabel(JLabel physicalLabel) {
        this.physicalLabel = physicalLabel;
    }

    public JTextField getPhysicalText() {
        return physicalText;
    }

    public JList<String> getCharacterJList() {
        return characterJList;
    }

    public void setCharacterJList(JList<String> characterJList) {
        this.characterJList = characterJList;
    }

    public void setPhysicalText(JTextField physicalText) {
        this.physicalText = physicalText;
    }

    public JRadioButton getRollRadioButton() {
        return rollRadioButton;
    }

    public void setRollRadioButton(JRadioButton rollRadioButton) {
        this.rollRadioButton = rollRadioButton;
    }

    public JLabel getStunLabel() {
        return stunLabel;
    }

    public void setStunLabel(JLabel stunLabel) {
        this.stunLabel = stunLabel;
    }

    public JTextField getStunText() {
        return stunText;
    }

    public void setStunText(JTextField stunText) {
        this.stunText = stunText;
    }

    public JButton getUpdateButton() {
        return updateButton;
    }

    public void setUpdateButton(JButton updateButton) {
        this.updateButton = updateButton;
    }
    
    public JButton getDeleteButton() {
        return deleteButton;
    }
    
    public JButton getRollDieButton(){
        return rollDieButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add5IniButton;
    private javax.swing.JList<String> characterJList;
    private javax.swing.JTextField characterToLoadText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JList<String> dieJList;
    private javax.swing.JLabel equalsLabel;
    private javax.swing.JButton forceRollButton;
    private javax.swing.JRadioButton healthRadioButton;
    private javax.swing.JLabel initiativeBonusLabel;
    private javax.swing.JTextField initiativeBonusText;
    private javax.swing.JLabel initiativeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadCharacterButton;
    private javax.swing.JButton makeHisTurnButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton nextTurnButton;
    private javax.swing.JTextField npcInitiativeText;
    private javax.swing.JTextField pcInitiativeText;
    private javax.swing.JLabel physicalLabel;
    private javax.swing.JTextField physicalText;
    private javax.swing.JButton rollDieButton;
    private javax.swing.JSpinner rollDieSpinner;
    private javax.swing.JRadioButton rollRadioButton;
    private javax.swing.JButton saveCharacterButton;
    private javax.swing.JButton sortListButton;
    private javax.swing.JLabel stunLabel;
    private javax.swing.JTextField stunText;
    private javax.swing.JButton substract5IniButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    public List<Character> getCharacters() {
        return characters;
    }

    public void setCharacters(List<Character> characters) {
        this.characters = characters;
    }

    public JList<String> getDieJList() {
        return dieJList;
    }

    public JButton getForceRollButton() {
        return forceRollButton;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JButton getMakeHisTurnButton() {
        return makeHisTurnButton;
    }
    
    JButton getAdd5IniButton() {
        return add5IniButton;
    }
    
    JButton getSubstract5IniButton() {
        return substract5IniButton;
    }
    
    JButton getLoadCharacterButton(){
        return loadCharacterButton;
    }
    
    JTextField getCharacterToLoadText(){
        return characterToLoadText;
    }
    
    JSpinner getRollDieSpinner(){
        return rollDieSpinner;
    }
}
